apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: staging-gateway
  namespace: staging
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-http01
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - int20h-staging.example.com
      secretName: staging-gateway-tls
  rules:
    - host: int20h-staging.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
