apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: edge-gateways
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    # Apply after core apps so backend Services already exist
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default

  source:
    repoURL: https://github.com/r4nol/int20h
    targetRevision: HEAD
    path: edge/gateways

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
