apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ingress-nginx.yaml
  - cert-manager.yaml
  - staging-project.yaml
  - production-project.yaml
  - boutique-staging.yaml
  - boutique-production.yaml
  - monitoring.yaml
  - edge-gateways.yaml
