apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../projects/staging-project.yaml
  - ../projects/production-project.yaml
  - boutique-staging.yaml
  - boutique-production.yaml
  - monitoring.yaml
